library(rprojroot)
library(arm)
library(MASS)
library(ggmap)
library(fs)
library(sf)
library(rstanarm)
library(arrow)
library(xtable)
library(tidycensus)
library(RColorBrewer)
library(scales)
library(yaml)
library(glue)
library(lubridate)
library(magrittr)
library(readxl)
library(rlang)
library(tidyverse)

options(mc.cores = parallel::detectCores())
options(tigris_use_cache = TRUE)
